formatter: "markdown"

content: |-
    ## Overview
    {{ include "overview.md" }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN OVERVIEW HOOK -->
    {{ .Content }}
    <!-- END OVERVIEW HOOK -->
