formatter: "markdown"

content: |-
    Table of Contents
    ====================

    {{ include "TOC.md" }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN TOC HOOK -->
    {{ .Content }}
    <!-- END TOC HOOK -->
