formatter: "markdown"

content: |-
    ## Updating template module content
    Most of the code for this module is stored in [common-dev-assets](https://github.com/terraform-ibm-modules/common-dev-assets). Therefore, to make any code changes to this module, files inside [module-assets/ci/module-template-automation](https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation) must be updated.

    If you would like to modify any markdown files then the code changes should be added to:
    - [Modifying main README file](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets/ci/module-template-automation/.terraform-docs-config-template-module.yaml)
    - [Modifying contributing section of main README file](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets/ci/module-template-automation/.terraform-docs-config-template-module-contribution.yaml)
    - [Modifying tests README file](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets/ci/module-template-automation/.terraform-docs-config-template-module-tests.yaml)

    To update `examples` the code inside [examples](https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation/examples) should be changed.

    To update `tests` the code inside [tests](https://github.com/terraform-ibm-modules/common-dev-assets/tree/main/module-assets/ci/module-template-automation/tests) should be changed.

    [build_module_template](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/module-assets/.pre-commit-config.yaml) pre-commit hook is used to build up the content for this module. The hook executes the following actions:
    - copies code, examples and tests from `common-dev-assets` into this module
    - creates markdown (README) files

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN UPDATING CODE HOOK -->
    {{ .Content }}
    <!-- END UPDATING CODE HOOK -->
