formatter: "markdown"

content: |-
    {{- $module_url:="" }}
    {{- range .Module.Inputs }}
        {{- if eq .Name "module-template" }}
          {{- $module_url = .Description }}
        {{- else if eq .Name "terraform-ibm-module-template" }}
          {{- $module_url = .Description }}
        {{- end }}
    {{- end }}
    // TODO: Update the module name here to match the GIT repo in which this file belongs to (remove the comment once done)
    module {{ $module_url }}

output:
  file: "tests/go.mod"
  mode: inject
  template: |-
    // START MODULE NAME HOOK
    {{ .Content }}
    // END MODULE NAME HOOK
