formatter: "markdown"

content: |-
    {{- $is_external:=false }}
    {{- $is_internal:=false }}
    {{- range .Module.Inputs }}
        {{- if eq .Name "module-template" }}
          {{- $is_internal = true }}
        {{- else if eq .Name "terraform-ibm-module-template" }}
          {{- $is_external = true }}
        {{- end }}
    {{- end }}
    # Tests

    For information about how to create and run tests, see [Validation tests]({{ if $is_internal }}https://github.ibm.com/GoldenEye/documentation/blob/master/tests.md{{- else if $is_external }}https://terraform-ibm-modules.github.io/documentation/#/tests{{ end }}) in the project documentation.

    <!-- Add any more steps that are specific to testing this module and that are not in the docs. -->

output:
  file: "tests/README.md"
  mode: inject
  template: |-
    <!-- BEGIN TESTS HOOK -->
    {{ .Content }}
    <!-- END TESTS HOOK -->
