default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: detect-private-key
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-angular']
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.74.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args: ['--args=--hide=providers']
    - id: terraform_tflint
      args:
#        NOTE: This is a subset of the rules usually used
        - --args=--enable-rule=terraform_deprecated_index
        - --args=--enable-rule=terraform_comment_syntax
        - --args=--enable-rule=terraform_naming_convention
        - --args=--enable-rule=terraform_required_version
        - --args=--enable-rule=terraform_required_providers
        - --args=--enable-rule=terraform_unused_required_providers
    - id: terragrunt_fmt
    - id: terraform_tfsec
      files: '\.tf'
    - id: terraform_checkov
      args:
        - --args=--skip-path=.scv
        - --args=--skip-path=Dockerfile
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.17
  hooks:
  - id: go-fmt
- repo: https://github.com/ibm/detect-secrets
  rev: 0.13.1+ibm.51.dss
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline', '--fail-on-unaudited', 'use-all-plugins']
    exclude: go.sum
# isort
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
# black
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
  - id: black
    args: # arguments to configure black
      - --line-length=88
